enum ACTION_TYPES {
    NEW_SCENARIO = '@GIP/NEW_SCENARIO',
    ADD_LINE_AFTER_CURRENT_LINE = '@GIP/ADD_LINE_AFTER_CURRENT_LINE',
    SET_DIALOG_TITLE = '@GIP/SET_DIALOG_TITLE',
    SET_DIALOG_INTRO = '@GIP/SET_DIALOG_INTRO'
}
export default ACTION_TYPES;
